version: '3'

services:

  addok:
    image: etalab/addok
    restart: unless-stopped
    networks:
      - traefik
    volumes:
    - ./addok-data/addok.conf:/etc/addok/addok.conf
    - ./addok-data/addok.db:/data/addok.db
    - ./logs:/logs
    links:
    - addok-redis
    environment:
      - WORKERS=8
      - LOG_QUERIES=1
      - LOG_NOT_FOUND=1
      - SLOW_QUERIES=200
    labels:
      - "traefik.enable=true" # Indique d'activer traefik pour ce container
      - "traefik.frontend.rule=PathPrefixStrip:/addok"
      - "traefik.port=7878"
      - "traefik.backend=addok"
      - "traefik.frontend.entryPoints=http"
      - "traefik.docker.network=traefik"

  addok-redis:
    image: etalab/addok-redis
    restart: unless-stopped
    networks:
      traefik:
        aliases:
          - redis
    volumes:
    - ./addok-data/dump.rdb:/data/dump.rdb
    labels:
      - "traefik.enable=true"
      - "traefik.backend=addok-redis"
      - "traefik.frontend.entryPoints=http"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
